# Generated by Django 5.1.3 on 2024-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Published'), (2, 'Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Member'), (2, 'Creator'), (3, 'blocked')], default=1),
        ),
    ]
