from django.urls import path
from . import views

urlpatterns = [
    path("",views.landing),
    path('login/', views.login),
    path('register/',views.registration),
    path('add_user/',views.register),
    path('log_user/',views.login_user),
    path('admin/',views.admin),
    path('logout/',views.logout_user),
    path('block/<int:id>/',views.block_user),
    path('block_event/<int:id>/',views.block_event),
    path('block_comment/<int:id>/',views.block_comment),
    path('publish_comment/<int:id>/',views.publish_comment),
    path('publish_event/<int:id>/',views.publish_event),
    path('view_event/<int:id>/',views.view_event),
    path('events/create/', views.create_event, name='create_event'),
    path('events/update/<int:event_id>/', views.update_event, name='update_event'),
    path('events/', views.list_events, name='list_events'),
    path('my_events/',views.my_events),
    path('join_event/<int:id>/',views.join_event),
    path('user_events/',views.user_events),
    path('unsave/<int:id>/',views.unsave),
    path('dashboard/',views.dashboard),
    path('favorite/<int:id>/',views.favorite),
    path('sports/',views.sports),
    path('arts/',views.arts),
    path('business/',views.business),
    path('education/',views.education),
    path('create/comment/<int:id>/',views.create_comment),
    path('end_join/<int:id>',views.end_join),
    path('creator/<int:id>',views.creator),
]